######################## Paper Information ########################################
# Personal info
paper_name: "LUCI: Lightweight UI Command Interface"

organization: EMBEDDED SYSTEMS WEEK 
sub_organization: CASES 
preprint : True

######################## Paper Resources ########################################

paper_pdf: https://dl.acm.org/doi/pdf/10.1145/3358198
# supplementary_pdf: Supplementary PDF here
code: https://github.com/MPSLab-ASU/Project_Page_Template
arXiv : https://arxiv.org/abs/1512.01274
IEEE: https://ieeexplore.ieee.org/document/9187262
# Additional icon links

favicon: assets/images/MPS_Lab.ico

main_media:
  source:  assets/images/architecture.png
  caption: \textbf{Architecture of LUCI}. Given user instruction and the conversational context, the Tool Selector first selects a tool from the given GUI toolset and opens the applications. The conversational model then generates a solution outline, which is a text description of the list of sub-tasks needed to solve the task. Next, the Task Verifier filters redundant tasks in the solution outline based on action feedback from previously executed tasks and future sub-tasks. Then, a rule-based UI Extractor extracts UI elements from the GUI application. UI Selector selects appropriate UI elements from the list of UI elements generated by the UI extractor for the given sub-task. Lastly, the Action Executor performs an action on the selected UI element based on the type of UI element and generates the action feedback



######################## DO NOT EDIT BELOW THIS LINE ########################################

# Footer
footer_show_references: true

#sass
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript


markdown: kramdown
permalink: pretty

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  "README.md",
  ]